### ISSUE TITLE
For some reason, the context of the widget is null

### ISSUE THREAD

**Issue by ibadaboom** [JosLuna98/overlay_screen#1]
The Widget is shown. If I try to pop the widget, I get this error:

flutter: Screen.showing
flutter: [NoSuchMethodError: The method 'findAncestorStateOfType' was called on null.

DebugInfos: 
```
dialogKey:"downloadProcedures"
overlayScreen:OverlayScreen
_customOverLayScreens:Map (2 items)
_overlayScreenContext:null
_state:Screen (Screen.showing)
hashCode:862896020
runtimeType:Type (OverlayScreen)
state:Screen (Screen.showing)
overlayText:"Updating weldprocedures..."
hashCode:907381286
runtimeType:Type (OverlayDialog)
```

**Comment by JosLuna98** [comment]
The overlay screen is now discontinued. I have created a new plugin easier to implement. 

https://pub.dev/packages/show_up/versions/1.0.0
