### ISSUE TITLE
Null safety migration

### ISSUE THREAD

**Issue by netgfx** [JosLuna98/overlay_screen#2]
Hello,

Has this been migrated to null safety? Thanks!

**Comment by abkorim1998** [comment]
hello
can we get a null safety version of it?  thanks

**Comment by JosLuna98** [comment]
I'm so sorry. Actually I thought that there would not be those who wanted this widget because it has not had much support.  I will migrate the plugin to null safety and then I will update it with some new ideas that I have implemented in my projects.

**Comment by JosLuna98** [comment]
@netgfx @abkorim1998 the plugin has been updated to null security, thanks for trusting and using it.

Like I said, I'll update it and give you all a better version. I'm already working on that.

**Comment by JosLuna98** [comment]
@netgfx @abkorim1998 
The overlay screen is now discontinued. I have created a new plugin easier to implement. 

https://pub.dev/packages/show_up/versions/1.0.0
