### ISSUE TITLE
The background is not totally transparent

### ISSUE THREAD

**Issue by mregnauld** [JosLuna98/overlay_screen#3]
I use `overlay_screen` to display a screen above my app, with transparents areas.
But when I use the following example:

```Dart
OverlayScreen().saveScreens({
  "test": CustomOverlayScreen(
    backgroundColor: Colors.transparent,
    content: SomeWidget(), 
  ),
});
```

the background is not totally transparent, unlike what I expected by using `backgroundColor: Colors.transparent`.

**Comment by JosLuna98** [comment]
I'm working in a new plugin with more functionalities and a best concept to replace overlay_screen.
overlay_screen will be discontinued soon, so I will not update it from now on.

**Comment by JosLuna98** [comment]
@mregnauld 
The overlay screen is now discontinued. I have created a new plugin easier to implement. 

https://pub.dev/packages/show_up/versions/1.0.0

**Comment by mregnauld** [comment]
OK, I'll try that out. Thanks!
